version: '3.4'

services:
  discountapi:
    image: discountapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9080:80"
    depends_on:
      - migrations
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "E21f90e!"
      ACCEPT_EULA: "Y"
    ports:
      - "14331:1433"
 